name: setup-python-and-install
description: Set up Python and optionally install packages
inputs:
  python-version:
    description: Python version to set up
    required: true
  packages:
    description: Space-separated pip packages to install
    required: false
    default: ""
runs:
  using: composite
  steps:
    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: ${{ inputs.python-version }}
    - name: Install packages
      if: ${{ inputs.packages != '' }}
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install ${{ inputs.packages }}
