# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build and test

on:
  push:
    branches: main
  pull_request_target:
    types: [labeled]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    if: contains(github.event.pull_request.labels.*.name, 'safe to test')
    - shell: bash
      run: cat tox.ini
